packages/polaris-viz/src/components/shared/HorizontalStackedBars/HorizontalStackedBars.tsx
Fixing a bug, horizontal stacked bar didn't display correctly when all values were negative.
Before:
After:
🎩 [Stacked Horizontal](http://localhost:6006/?path=/story/polaris-viz-charts-barchart--stacked&args=data[0].data[1].value:0;direction:horizontal)
=> fix bug - display negative values for stacked horizontal chart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/Points/Points.tsx, packages/polaris-viz/src/components/StackedAreaChart/stories/Playground.stories.tsx
When `<StackedAreaChart />` was not animated we were not returning the correct x/y values when hovering over different points.
Resolves https://github.com/Shopify/polaris-viz/issues/1355
**Before**
https://user-images.githubusercontent.com/149873/184239062-8ba3b4f3-d6a5-4ef3-95b7-b51c1b394070.mov
**After**
https://user-images.githubusercontent.com/149873/184238879-02e2c17c-e8bf-4d18-8286-a8433bbc4af7.mov
=> Position points correctly when not animated

packages/polaris-viz-core/src/utilities/getRoundedRectPath.ts, packages/polaris-viz-core/src/utilities/stories/getRoundedRectPath.chromatic.stories.tsx, packages/polaris-viz-core/src/utilities/tests/getRoundedRectPath.test.ts
If the combined radius of the border was larger than either the height or width, a rect would draw all funky.
Our previous fix was to just remove the rounded borders and draw a basic rectangle.
Now that we allow users to set their own border radius via the theme, I think it's better is we still render a rounded corner, but clamp it to the largest radius we can use without breaking the rect.
https://6062ad4a2d14cd0021539c1b-oginxkncbh.chromatic.com/?path=/story/chromatic-utilities-getroundedrectpath--horizontal
=> Clamp large rounded corners to bar dimensions

packages/polaris-viz-core/src/constants.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/components/Points/Points.tsx, packages/polaris-viz/src/components/LineChart/components/PointsAndCrosshair/PointsAndCrosshair.tsx, packages/polaris-viz/src/components/Point/Point.tsx, packages/polaris-viz/src/components/Point/tests/Point.test.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/Points/Points.tsx
The color value being used for the `<Point />` stroke in the `Default` theme was wrapped in quotes, so the color being passed was invalid.
Resolves https://github.com/Shopify/polaris-viz/issues/1158
|---|---|
|<img width="99" alt="image" src="https://user-images.githubusercontent.com/149873/184419409-6d031a07-38a6-46ae-b1c6-4850e741fa3f.png">|<img width="124" alt="image" src="https://user-images.githubusercontent.com/149873/184419350-65c76a5b-b7fa-4288-82bf-54675aaa8e0d.png">|
=> Fixed wrong color being used for Point stroke

packages/polaris-viz/src/components/SimpleNormalizedChart/SimpleNormalizedChart.scss, packages/polaris-viz/src/components/SquareColorPreview/SquareColorPreview.scss, packages/polaris-viz/src/styles/_common.scss
Add css class to force the browser to include the background color when printing.
Resolves https://github.com/Shopify/polaris-viz/issues/1262
=> Include SquareColorPreview when printing

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/HorizontalBarChart/Chart.tsx, packages/polaris-viz/src/components/SimpleBarChart/Chart.tsx, packages/polaris-viz/src/components/SimpleBarChart/stories/SimpleBarChart.stories.tsx, packages/polaris-viz/src/components/shared/Bar/Bar.tsx, packages/polaris-viz/src/components/shared/Bar/tests/Bar.test.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/HorizontalBars.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/Label/Label.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/index.ts, packages/polaris-viz/src/components/shared/HorizontalGroup/HorizontalGroup.tsx, packages/polaris-viz/src/components/shared/index.ts, packages/polaris-viz/src/hooks/useBarSpringConfig.ts
Horizontal Bars were not animating and we're also animating up on mount (fixed in https://github.com/Shopify/polaris-viz/pull/1357).
**Old and busted**
https://user-images.githubusercontent.com/149873/184178398-6994b274-b280-46c4-a2c8-711a4bfd705f.mov
**New and shiny**
https://user-images.githubusercontent.com/149873/184179309-a034ccd4-1a29-4e2d-813e-b63f44e47406.mov
- [HorizontalBarChart](https://6062ad4a2d14cd0021539c1b-slbqyxkzau.chromatic.com/?path=/story/polaris-viz-charts-barchart--default&args=direction:horizontal)
- [SimpleBarChart](https://6062ad4a2d14cd0021539c1b-slbqyxkzau.chromatic.com/?path=/story/polaris-viz-charts-simplebarchart--default)
=> Fix animation for horizontal bars

.github/probots.yml, .github/workflows/cla.yml
Probots has be deprecated. This replaces the CLA with a github action.
Resolves https://github.com/Shopify/polaris-viz/issues/1366
=> Replace probots-cla with github action

CONTRIBUTING.md, LOCAL_DEVELOPMENT.md, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/storybook/index.ts, scripts/character-widths/README.md
`polaris-viz.shopify.io` does not seem to exist. `polaris-viz.shopify.com` is interspersed throughout the code. Change all references from `.io` to `.com` in the READMEs, etc
Did not change the `CHANGELOG` as it's historical
Finally, change the storybook definition in `RENDER_TOOLTIP_DESCRIPTION` because it's used in the site to link back, and that link was broken.
=> Change polaris-viz.shopify.io -> .com

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/BarChart.tsx, packages/polaris-viz/src/components/FunnelChart/FunnelChart.tsx, packages/polaris-viz/src/components/LineChart/LineChart.tsx, packages/polaris-viz/src/components/LineChart/stories/Annotations.stories.tsx, packages/polaris-viz/src/components/SimpleBarChart/SimpleBarChart.tsx, packages/polaris-viz/src/components/SparkBarChart/SparkBarChart.tsx, packages/polaris-viz/src/components/SparkLineChart/SparkLineChart.tsx, packages/polaris-viz/src/components/SparkLineChart/stories/meta.tsx, packages/polaris-viz/src/components/StackedAreaChart/StackedAreaChart.tsx
We weren't passing `theme` down to `<ChartSkeleton />` which was causing it to always render the `Default` theme.
|---|---|
|<img width="263" alt="image" src="https://user-images.githubusercontent.com/149873/187237112-ffae53f1-5560-4a1a-887d-7a19fb088831.png">|<img width="260" alt="image" src="https://user-images.githubusercontent.com/149873/187237021-4bea98e4-e999-46ce-9a1b-05474c9db83a.png">|
=> Pass theme to ChartSkeleton

.gitignore, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/hooks/useLinearLabelsAndDimensions.ts
In order to center points over the labels on linear charts, we inset the `<LineSeries />` by half of the label width.
When the labels are hidden, we don't need to inset the series anymore. 
Resolves https://github.com/Shopify/polaris-viz/issues/1368
|---|---|
|![image](https://user-images.githubusercontent.com/149873/187709675-b9720889-3cd2-443f-8b23-40a0a542c359.png)|![image](https://user-images.githubusercontent.com/149873/187709604-d35c65d3-cd21-456e-8372-8cb85dacee01.png)|
=> Don't inset LineSeries when labels are hidden

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/ChartSkeleton/components/ErrorText/ErrorText.tsx, packages/polaris-viz/src/components/ComboChart/Chart.tsx, packages/polaris-viz/src/components/FunnelChart/Chart.tsx, packages/polaris-viz/src/components/FunnelChart/components/FunnelChartXAxisArrows.tsx, packages/polaris-viz/src/components/FunnelChart/components/FunnelChartXAxisLabels.tsx, packages/polaris-viz/src/components/HorizontalBarChart/Chart.tsx, packages/polaris-viz/src/components/HorizontalBarChartXAxisLabels/HorizontalBarChartXAxisLabels.tsx, packages/polaris-viz/src/components/Labels/Labels.chromatic.stories.tsx, packages/polaris-viz/src/components/Labels/hooks/useLabels.tsx, packages/polaris-viz/src/components/Labels/utilities/getDiagonalLabels.ts, packages/polaris-viz/src/components/Labels/utilities/getVerticalLabels.ts, packages/polaris-viz/src/components/Labels/utilities/truncateSingleLine.ts, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/components/XAxis/XAxis.tsx
The notebooks team reported a case where labels were jumping around again at certain chart sizes.
Diagonal and Horizontal labels don't really need to take the chart height into account because they have a set maximum size, so by using the chart height we would get into a condition where the truncation was flipping back and forth because the chart height was changing too often.
**Original Issue**
https://user-images.githubusercontent.com/149873/187736243-09b2fadb-78bb-4cd4-b0a3-6e2e19d04639.mp4
**Fix**
https://user-images.githubusercontent.com/149873/187736618-5123fdbc-1cc2-4bb2-824a-e9fe69d990eb.mov
https://6062ad4a2d14cd0021539c1b-jokmkybbaz.chromatic.com/iframe.html?args=&id=polaris-viz-charts-barchart-playground--jumpy-labels-from-notebooks&viewMode=story
=> Fix jumping labels again

.github/workflows/chromatic.yml, packages/polaris-viz-core/src/constants.ts
Block PRs from merging if chromatic has visual changes.
Resolves https://github.com/Shopify/polaris-viz/issues/1309
=> Block PRs when chromatic has changes

packages/polaris-viz-core/src/index.ts, packages/polaris-viz-core/src/utilities/index.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/ChartContainer/ChartContainer.tsx, packages/polaris-viz/src/components/ChartContainer/components/ChartDimensions/ChartDimensions.tsx, packages/polaris-viz/src/components/ChartErrorBoundary/ChartErrorBoundary.tsx, packages/polaris-viz/src/components/ChartErrorBoundary/tests/ChartErrorBoundary.test.tsx, packages/polaris-viz/src/components/ChartErrorBoundary/utilities/checkForMismatchedData.ts, packages/polaris-viz/src/components/HorizontalBarChart/Chart.tsx, packages/polaris-viz/src/components/HorizontalBarChart/tests/Chart.test.tsx, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/LineChart/tests/Chart.test.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/StackedAreaChart/tests/Chart.test.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/tests/Chart.test.tsx
When a data series has an empty data array, some of the charts will error because the tooltips expect valid data.
```
[{name: 'Empty', data: []}]
```
Instead of checking for bad data, we can not render the `<TooltipWrapper />`.
I also added a warning in the console if the user passes mismatched data series. Currently the chart goes into an error state, but the consumer may not know why.
Resolves https://github.com/Shopify/polaris-viz/issues/1328
=> Don't render TooltipWrapper when data could be bad

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/meta.tsx, packages/polaris-viz/src/components/LineChart/constants.ts, packages/polaris-viz/src/components/VerticalBarChart/components/StackedBarGroups/StackedBarGroups.tsx, packages/polaris-viz/src/components/VerticalBarChart/components/StackedBarGroups/components/Stack/Stack.tsx, packages/polaris-viz/src/components/VerticalBarChart/components/VerticalBarGroup/VerticalBarGroup.tsx, packages/polaris-viz/src/storybook/constants.ts, packages/polaris-viz/src/utilities/getLoadAnimationDelay.ts
Added load animations for stacked vertical bar charts.
=> Add load animation to vertical stacked bar charts

packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx
In some charts, we have to call `useYScale` twice. Once to get initial values and then a second time once the chart has resized itself based on labels & legends.
We were passing the same data twice, which lends itself to bugs.
=> Use a single options object for useYScale

packages/polaris-viz/src/components/BarChart/stories/BarChart.chromatic.stories.tsx, packages/polaris-viz/src/components/StackedAreaChart/hooks/useStackedData.ts, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/hooks/useHorizontalStackedValues.ts, packages/polaris-viz/src/utilities/getStackedValues.ts, packages/polaris-viz/src/utilities/tests/getStackedValues.test.tsx
Use a unique key for stacked values in case the consumer doesn't use a unique name for each data series.
Resolves https://github.com/Shopify/polaris-viz/issues/153
Nothing would crash the charts, but the logic for figuring out which stack needed rounded corners would be wrong.
|---|---|
|![image](https://user-images.githubusercontent.com/149873/188935096-465fadcd-a77a-4713-9e9e-e7f52aad0dd4.png)|![image](https://user-images.githubusercontent.com/149873/188935032-27206b62-18e4-4b74-af2e-08e35125a696.png)|
=> Use unique values for stack() keys

packages/polaris-viz-core/src/components/LineSeries/components/AnimatedArea/AnimatedArea.tsx, packages/polaris-viz-core/src/components/LineSeries/components/AnimatedLine/AnimatedLine.tsx, packages/polaris-viz-core/src/constants.ts, packages/polaris-viz-core/src/hooks/index.ts, packages/polaris-viz-core/src/hooks/useSpringConfig.ts, packages/polaris-viz-core/src/index.ts, packages/polaris-viz/src/components/Arc/Arc.tsx, packages/polaris-viz/src/components/BarChart/stories/DynamicData.stories.tsx, packages/polaris-viz/src/components/FunnelChart/components/FunnelSegment.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/components/BarSegment/BarSegment.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/Area/Area.tsx, packages/polaris-viz/src/components/StackedAreaChart/stories/DynamicData.stories.tsx, packages/polaris-viz/src/components/VerticalBarChart/components/BarGroup/BarGroup.tsx, packages/polaris-viz/src/components/VerticalBarChart/components/VerticalBar/VerticalBar.tsx, packages/polaris-viz/src/components/shared/HorizontalStackedBars/HorizontalStackedBars.tsx, packages/polaris-viz/src/components/shared/HorizontalStackedBars/components/StackedBar/StackedBar.tsx, packages/polaris-viz/src/hooks/useBarSpringConfig.ts
We were using the same logic for setting mounted/unmounted state in `useSpring` config, so now we have a single hook that takes care of everything.
Nothing should look different.
=> Unify spring config logic

packages/polaris-viz/src/components/LineChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/TooltipContent/hooks/tests/useGetLongestLabelFromData.test.tsx, packages/polaris-viz/src/components/TooltipContent/hooks/useGetLongestLabelFromData.ts
Sometimes the data passed into tooltip is empty:
This is causing the LineChart component to break when mousing further right than the existing data. This PR ensures that the data exists before referencing it.
Closes https://github.com/Shopify/core-issues/issues/45475
=> Account for empty tooltip data

packages/polaris-viz-core/CHANGELOG.md, packages/polaris-viz-core/src/components/LineSeries/LineSeries.tsx
Fixes the following Android error when importing `SparkLineChart` on Android.
https://user-images.githubusercontent.com/4960217/196744064-d517105a-a01a-4f89-95b2-f9d40d59811f.png
Closes: https://github.com/Shopify/polaris-viz/issues/1404
=> Set `solid` value `none` for `LineSeries` in core

packages/polaris-viz-core/loom.config.ts, packages/polaris-viz-native/loom.config.ts, packages/polaris-viz/loom.config.ts
Moving from `transformIgnorePatterns` which requires d3 packages to be transpiled.
Transpiling has a speed hit so moving to the built versions of d3 in jest is faster.
=> Use dist versions of d3 when testing

packages/polaris-viz-core/src/components/LineSeries/LineSeries.tsx, packages/polaris-viz-core/src/components/LineSeries/tests/LineSeries.test.tsx, packages/polaris-viz/CHANGELOG.md
The mask wasn't tall enough for the stroke of the line. This was causing the line to get cut off at the 0 line.
Resolves https://github.com/Shopify/core-issues/issues/45442
|---|---|
|![image](https://user-images.githubusercontent.com/149873/198058678-a3b6c93e-f11c-42e1-8484-67349688899a.png)|![image](https://user-images.githubusercontent.com/149873/198058488-05100ee9-cad4-4e67-881a-c5dbc34c90f4.png)|
https://6062ad4a2d14cd0021539c1b-bdssklfvha.chromatic.com/?path=/story/polaris-viz-charts-linechart-playground--cohort-comparison-data-set
=> Fix LineSeries being cut off at bottom of the chart

packages/polaris-viz-core/CHANGELOG.md, packages/polaris-viz-core/src/components/LineSeries/LineSeries.tsx, packages/polaris-viz-core/src/styles/shared/_variables.scss, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/LineChart.tsx
Changes the contrast levels for the comparison dots in the line chart.
closes #1413 
|---|---|
|  <img width="840" alt="Screen Shot 2022-10-28 at 12 41 41 PM" src="https://user-images.githubusercontent.com/36030324/198702025-2d57d179-1ebd-4a70-ba1c-5f5ddfc55284.png"> |  
|
=> Fixes accessibility issues in the line chart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/ComboChart/Chart.tsx, packages/polaris-viz/src/components/ComboChart/stories/playground/Playground.stories.tsx
When getting the position for the tooltip, the wrong `yScale` was being used which would sometimes render the `<Tooltip />` outside the chart bounds because the y value was huge.
We always want to use the bar chart data as the positioning for the tooltip.
**Video of the bug**
https://user-images.githubusercontent.com/149873/200875025-e979ce2d-44c4-460d-b6bc-11a7ab169c9b.mov
https://6062ad4a2d14cd0021539c1b-xfoasitseo.chromatic.com/?path=/story/polaris-viz-charts-combochart-playground--web-vitals
=> Use Bar data for yScale

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/Chart.tsx
The logic to position the tooltip was still being positioned as if the lines were offset from the labels. With the recent changes (https://github.com/Shopify/polaris-viz/pull/1411) to not offset the labels, this was missed.
Resolves https://github.com/Shopify/polaris-viz/issues/1435
Resolves https://github.com/Shopify/core-issues/issues/47488
**Before**
https://user-images.githubusercontent.com/149873/201779284-8d192f8e-83cf-47a8-8684-60b8f02f7fe6.mov
**After**
https://user-images.githubusercontent.com/149873/201779172-6bb62bc4-a3ac-4b13-8ed0-6df6a8d3c727.mov
=> Fix LineChart tooltip being offset from mouse

packages/polaris-viz-core/CHANGELOG.md, packages/polaris-viz-core/src/components/LineSeries/LineSeries.tsx
Increases sparkline chart's stroke width
Before:
After:
Resolves [#1421](https://github.com/Shopify/polaris-viz/issues/1421)
=> update line stroke width for spark line chart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/hooks/useStackedData.ts, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/hooks/tests/useIndexForLabels.test.tsx, packages/polaris-viz/src/hooks/useIndexForLabels.ts
Based on some feedback from @susiekims the logic we used to determine which `DataSeries` we used for labels was different between `LineChart` and `BarChart`.
The original change was introduce to `LineChart` as part of https://github.com/Shopify/polaris-viz/pull/1411.
In `BarChart` we would loop through each `DataSeries` and overwrite the array of labels on each pass. This means that in most cases we used the labels from the last item in the array. This was to make sure we always displayed the correct amount of labels for `DataSeries` that don't contain matching lengths.
|---|---|
|![image](https://user-images.githubusercontent.com/149873/204326285-bd119562-9dc0-4923-bad9-cc149bb92d62.png)|![image](https://user-images.githubusercontent.com/149873/204326121-53799fa9-dcda …
=> Use longest matching index for bar and line charts

packages/polaris-viz-core/src/types.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/Docs/stories/arc.stories.mdx, packages/polaris-viz/src/components/Docs/stories/components/SampleComponents.tsx, packages/polaris-viz/src/components/Docs/stories/components/index.ts, packages/polaris-viz/src/components/DonutChart/stories/CustomArcWidth.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/CustomColors.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/Default.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/DynamicData.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/ErrorState.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/InteractiveCustomLegend.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/SingleDataPoint.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/WithoutRoundedCorners.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/data.tsx
This PR adds the `arc` property to the `PartialTheme` type. This will allow developers to override the default value when instantiating a `DonutChart` component – through the usage of the `PolarisVizProvider.theme` prop.
Example usage:
```tsx
<PolarisVizProvider
themes={{
Default: {
arc: {
borderRadius: 0,
thickness: 10,
}
}
}}
>
<DonutChart data={data} />
</PolarisVizProvider>
```
The `DonutChart` component already had the scaffolding in place to support this functionality, we just needed to add `arc: Partial<ArcTheme>` to the `PartialTheme` type to prevent type errors during usage.
Additionally, this PR includes documentation of the chart-specific property `arc` and some minor cleanup within the `DonutChart` stories.
N/A
Docs example:
`thickness: 50`
`cornerRadius: 0`
- …
=> Allow ability to override `arc` in Theme

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx
We weren't using the correct with in `BarChart` when rendering the grid lines. This PR takes into account the `grid.horizontalOverflow` value.
Resolves https://github.com/Shopify/polaris-viz/issues/1448
|---|---|
|![image](https://user-images.githubusercontent.com/149873/207643488-6f834f50-124f-41c3-9e98-d26118fff25c.png)|![image](https://user-images.githubusercontent.com/149873/207643651-d121d8ec-087b-44b3-8c8d-b23103a59d7e.png)|
=> Use correct width based on grid.horizontalOverflow value

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/DonutChart/DonutChart.tsx, packages/polaris-viz/src/components/DonutChart/stories/CustomArcWidth.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/DynamicData.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/LegendFullWidth.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/WithoutRoundedCorners.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/data.tsx, packages/polaris-viz/src/components/DonutChart/stories/meta.tsx, packages/polaris-viz/src/components/LegendContainer/LegendContainer.tsx, packages/polaris-viz/src/storybook/constants.ts
This PR adds a `legendFullWidth` property to `<DonutChart />` to allow users the ability to specify whether they want the legend to take up the full width of the chart container (or not). By default, if no value is provided, this prop will take on the value `false`.
This will allow users to make more customizable legends with the `renderLegendContent` prop (i.e., not limited by the `maxWidth` style that is currently being set).
N/A
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/44531733/209022676-1c5fab26-dd02-4b97-9323-eb87b0af1b3a.png) | ![image](https://user-images.githubusercontent.com/44531733/209022712-c0d539af-f113-4987-89f8-928256e5d1e7.png) |
The `before` image shows what the text looks like with a container chart width of 550px, whereas the …
=> Add `legendFullWidth` prop to `<DonutChart />`

packages/polaris-viz/src/components/SwallowErrors/SwallowErrors.tsx, packages/polaris-viz/src/components/SwallowErrors/index.ts, packages/polaris-viz/src/components/TooltipWrapper/TooltipWrapper.tsx
We've had an issue where if the data in a tooltip is accessed incorrectly, or not available at all, the Tooltip will crash the entire chart.
Would it make sense to swallow those errors and not render the Tooltip at all? Does this change make sense at all/is it necessary?
**Before**
https://user-images.githubusercontent.com/149873/213560416-7fb1749b-2c29-40e4-ac6e-0efcca19c7d2.mov
**After**
https://user-images.githubusercontent.com/149873/213560602-ea4d959b-67c2-4601-b79b-fd6a8006ed76.mov
=> Swallow Tooltip errors instead of crashing the chart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/ChartSkeleton/ChartSkeleton.tsx, packages/polaris-viz/src/components/ChartSkeleton/components/DonutSkeleton/DonutSkeleton.tsx, packages/polaris-viz/src/components/ChartSkeleton/components/FunnelSkeleton/FunnelSkeleton.tsx, packages/polaris-viz/src/components/ChartSkeleton/components/GridSkeleton/GridSkeleton.tsx, packages/polaris-viz/src/components/ChartSkeleton/components/SimpleBarSkeleton/SimpleBarSkeleton.tsx, packages/polaris-viz/src/components/ChartSkeleton/components/SimpleNormalizedSkeleton/SimpleNormalizedSkeleton.scss, packages/polaris-viz/src/components/ChartSkeleton/components/SimpleNormalizedSkeleton/SimpleNormalizedSkeleton.tsx, packages/polaris-viz/src/components/ChartSkeleton/components/SparkSkeleton/SparkSkeleton.tsx, packages/polaris-viz/src/components/ChartSkeleton/index.ts, packages/polaris-viz/src/components/SimpleNormalizedChart/SimpleNormalizedChart.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/stories/ErrorState.stories.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/stories/LoadingState.stories.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/stories/LoadingStateWithMediumSize.stories.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/stories/LoadingStateWithoutLegend.stories.tsx
This is a remake of https://github.com/Shopify/polaris-viz/pull/1463, which was already approved – however I didn't realize the base branch wasn't automatically updated to `main` before I merged. I've rebased this branch onto main here so it can be merged correctly.
N/A
N/A
https://6062ad4a2d14cd0021539c1b-iqwujydnfj.chromatic.com/?path=/story/intro--page
=> Clean up `<SimpleNormalizedChart />` loading state [remake]

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/components/Points/Points.tsx, packages/polaris-viz/src/components/LineChart/components/PointsAndCrosshair/PointsAndCrosshair.tsx, packages/polaris-viz/src/components/LineChart/stories/playground/Playground.stories.tsx
Fixed a bug where data will null values would throw the calculations for all points after it off. Now the points will animate in/out when the value is null or not.
Also fixes a bug where point animations were not animating the x value. The video below poorly explains the issue.
https://user-images.githubusercontent.com/149873/217663052-363cf9d0-dab2-44c4-bead-9c2da447544b.mov
Resolves https://github.com/Shopify/polaris-viz/issues/1439 
https://user-images.githubusercontent.com/149873/217663123-41da1639-7158-41c9-b8ea-0b04248c3db0.mov
https://6062ad4a2d14cd0021539c1b-jaltxmiiji.chromatic.com/?path=/story/polaris-viz-charts-linechart-playground--patchy-data
=> Fix bug where points with null data threw all points off

packages/polaris-viz-core/src/constants.ts, packages/polaris-viz-core/src/styles/shared/_variables.scss, packages/polaris-viz-core/src/types.ts, packages/polaris-viz/src/components/TrendIndicator/TrendIndicator.tsx, packages/polaris-viz/src/components/TrendIndicator/components/Arrows/ArrowDown.tsx, packages/polaris-viz/src/components/TrendIndicator/components/Arrows/ArrowUp.tsx, packages/polaris-viz/src/components/TrendIndicator/components/Arrows/index.ts, packages/polaris-viz/src/components/TrendIndicator/components/Svg/Svg.scss, packages/polaris-viz/src/components/TrendIndicator/components/Svg/Svg.tsx, packages/polaris-viz/src/components/TrendIndicator/components/Svg/index.ts, packages/polaris-viz/src/components/TrendIndicator/components/index.ts, packages/polaris-viz/src/components/TrendIndicator/index.ts, packages/polaris-viz/src/components/TrendIndicator/stories/Default.stories.tsx, packages/polaris-viz/src/components/TrendIndicator/stories/TrendIndicator.chromatic.stories.tsx, packages/polaris-viz/src/components/TrendIndicator/stories/data.tsx, packages/polaris-viz/src/components/TrendIndicator/stories/meta.tsx, packages/polaris-viz/src/components/index.ts, packages/polaris-viz/src/index.ts, packages/polaris-viz/src/types.ts, scripts/character-widths/build-character-widths.html
Initial exploration for a TrendIndicator component that can be used in `web`.
There was an ask about adding these TrendIndicators in charts like Funnel and SimpleBarChart.
To allow the TrendIndicator to be an inline element in the chart, and be copyable/printable, it needs to be an svg element. 
Thoughts @pbojinov @LBWright @nickpresta @philschoefer? Is it worth supporting an SVG element instead of just plain ol' HTML?
https://6062ad4a2d14cd0021539c1b-tneqaezlby.chromatic.com/?path=/story/polaris-viz-subcomponents-trendindicator--default
https://6062ad4a2d14cd0021539c1b-tneqaezlby.chromatic.com/?path=/story/chromatic-components--trendindicator
=> Add TrendIndicator

.github/workflows/size-limit.yml
Fixes an issue causing `size-limit` to fail because `graphql-typescript-definitions` depends on `@apollo/federation `which refuses to install on node 18.
```
yarn why @apollo/federation
Found existing alias for "yarn". You should use: "y"
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "@apollo/federation"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@apollo/federation@0.27.0"
info Reasons this module exists
- "_project_#@shopify#loom-plugin-build-library-extended#graphql-typescript-definitions#graphql-tool-utilities#apollo-codegen-core#apollo-language-server" depends on it
- Hoisted from "_project_#@shopify#loom-plugin-build-library-extended#graphql-typescript-definitions#graphql-tool-utilities#apollo-codegen …
```
=> Fix issue with size-limit node version mismatch

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/utilities/getAlteredLineChartPosition.ts, packages/polaris-viz/src/components/LineChart/utilities/index.ts, packages/polaris-viz/src/components/LineChart/utilities/tests/getAlteredLineChartPosition.test.ts
The `<LineChart />` tooltip would try and follow the cursor around when interacting with the chart. This allowed the tooltip to get into a state where it was covering the crosshair for the active state, which covers the data.
Now, we're going to make the tooltip never cover the crosshair. It will always try and render on either side of the crosshair that keeps the tooltip within the bounds of the chart.
**Before**
https://user-images.githubusercontent.com/149873/223225806-da4465fa-f095-49fd-b0f7-cf32c8474a95.mov
**After**
https://user-images.githubusercontent.com/149873/223225878-fe9d4823-375d-40e1-8cb8-516b7d0da4e1.mov
=> Stop the tooltip from covering the crosshair

packages/polaris-viz/src/components/LineChart/components/Points/Points.tsx, packages/polaris-viz/src/components/LineChart/hooks/useLineChartTooltipContent.ts, packages/polaris-viz/src/components/TooltipContent/TooltipContent.tsx, packages/polaris-viz/src/components/TooltipContent/components/TooltipRow/TooltipRow.tsx, packages/polaris-viz/src/hooks/ColorVisionA11y/useColorVisionEvents.ts, packages/polaris-viz/src/playground/ExternalEvents.stories.tsx, packages/polaris-viz/src/types.ts
I introduced a bug where the points on a line chart wouldn't show up unless you were hovering over a line. The points should always show and then hide all inactive points when hovering a line.
Resolves https://github.com/Shopify/core-issues/issues/53198
- https://6062ad4a2d14cd0021539c1b-desuufdvxo.chromatic.com/?path=/story/polaris-viz-charts-linechart--default
I also noticed an issue where tooltip items wouldn't highlight correctly if some of the lines had been hidden.
https://6062ad4a2d14cd0021539c1b-desuufdvxo.chromatic.com/?path=/story/polaris-viz-playground-externalevents--hide-lines
- Have at least 2 lines visible
- Tooltip should show correct data AND highlight correctly when hovering lines.
|---|---| …
=> Fix points not rendering when no active line

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LinePreview/LinePreview.scss
The SVG was cutting off the right side of the LinePreview icon.
|---|---|
|![image](https://user-images.githubusercontent.com/149873/228295936-8986447e-74b7-4014-8c60-5e34b82a7886.png)|![image](https://user-images.githubusercontent.com/149873/228295382-662023de-651c-457e-a75d-36dcd8edd602.png)|
=> Fix line being cut off on right side

packages/polaris-viz/src/components/TooltipContent/TooltipContent.tsx, packages/polaris-viz/src/components/TooltipContent/components/TooltipContentContainer/TooltipContentContainer.tsx, packages/polaris-viz/src/utilities/renderLinearTooltipContent.tsx
The `renderLinearTooltipContent` component wasn't using the colorvision active states to highlight the different items. 
I've refactored the `<TooltipContentContainer />` to push the `activeIndex` so we only have to watch for events in a single place.
https://user-images.githubusercontent.com/149873/228330487-f5b382ae-b235-41ff-a78b-3f1fb04e5cac.mov
https://user-images.githubusercontent.com/149873/228330531-28051f27-f6e3-49ab-be1c-e9e74cfdf124.mov
https://6062ad4a2d14cd0021539c1b-lwydmnlqii.chromatic.com/?path=/story/polaris-viz-charts-barchart--default
https://6062ad4a2d14cd0021539c1b-lwydmnlqii.chromatic.com/?path=/story/polaris-viz-charts-linechart-playground--linear-comparison-tooltip
https://6062ad4a2d14cd0021539c1b-lwydmnlqii.chromatic.com/?path=/story/polaris-viz-charts-linechartrel …
=> Push active state to all tooltips

packages/polaris-viz-core/src/components/LineSeries/LineSeries.tsx, packages/polaris-viz-core/src/types.ts, packages/polaris-viz/src/components/LineChartRelational/components/Area/Area.tsx, packages/polaris-viz/src/components/LineChartRelational/stories/data.tsx
We're making the hit area of lines a little smaller so they don't get jumbled up when lots of lines are close together.
We're also going to fade out all the related areas in `<LineChartRelational />` when hovering lines.
Resolves https://github.com/Shopify/core-issues/issues/53555
Resolves https://github.com/Shopify/core-issues/issues/53565
|---|---|
|![image](https://user-images.githubusercontent.com/149873/229833016-c8a27654-8a5e-4832-b2be-07857e8983bd.png)|![image](https://user-images.githubusercontent.com/149873/229833061-29893ef3-9f6b-40ca-8165-ff54cfd2c857.png)|
https://6062ad4a2d14cd0021539c1b-oiaxhtpomj.chromatic.com/?path=/story/polaris-viz-charts-linechartrelational--default&args=theme:Light
=> Make LineSeries hit area smaller. Fade out RelatedAreas more

packages/polaris-viz/CHANGELOG.md
Missed a CHANGELOG entry for a breaking rename.
=> Add rename of renderLinearComparisonTooltip

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChartRelational/components/MissingDataArea/MissingDataArea.tsx, packages/polaris-viz/src/components/LineChartRelational/components/MissingDataArea/tests/MissingDataArea.test.tsx, packages/polaris-viz/src/components/LineChartRelational/components/MissingDataArea/utilities/groupNumbersIntoRuns.ts, packages/polaris-viz/src/components/LineChartRelational/stories/chromatic/MissingData.chromatic.stories.tsx, packages/polaris-viz/src/components/LineChartRelational/stories/chromatic/data/missing-end-data.js, packages/polaris-viz/src/components/LineChartRelational/stories/chromatic/data/missing-middle-data.js, packages/polaris-viz/src/components/LineChartRelational/stories/chromatic/data/missing-random-data.js, packages/polaris-viz/src/components/LineChartRelational/stories/chromatic/data/missing-start-data.js, packages/polaris-viz/src/utilities/renderLinearTooltipContent.tsx
It was assumed that the missing data for benchmarks would always be at the end of the chart, but that was wrong.
We want t be able to render the diagonal lines wherever the data is actually missing, instead of assuming the end.
Currently in web [we are stripping `null` values from benchmarks](https://github.com/Shopify/web/blob/93d1c4f64612b5c02447bc2c95624c7a8e32d98b/app/sections/Analytics/ReportViewer/components/ReportViewer/components/Chart/components/LineChartRelational/LineChartRelational.tsx#L43), which originally resulted in arrays with different lengths. We don't want to do this anymore because it's also positioning the benchmark lines always at the beginning of the chart.
Resolves https://github.com/Shopify/core-issues/issues/54090 …
=> Allow MissingDataArea to render anywhere on the chart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/ChartSkeleton/components/ErrorText/ErrorText.tsx, packages/polaris-viz/src/components/SparkLineChart/stories/ErrorState.stories.tsx
The ErrorText component was allowing a negative Y-axis translation that cut off the text when viewing on a very short SparkLineChart. It was also not really centering the text because it was multiplying the font size by 2 instead of dividing it by 2.
|---|---|
| <img width="1495" alt="image" src="https://user-images.githubusercontent.com/1236959/235499946-ff748949-1e17-4ef4-8012-b994892be759.png"> |  <img width="1472" alt="image" src="https://user-images.githubusercontent.com/1236959/235499802-498758d0-7d87-474c-9dd1-8a4f7a16e88d.png"> |
=> Fix ErrorText positioning in ChartSkeleton

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/Chart.tsx, packages/polaris-viz/src/components/SimpleBarChart/SimpleBarChart.tsx, packages/polaris-viz/src/components/SimpleBarChart/index.ts, packages/polaris-viz/src/components/SimpleBarChart/stories/MultipleTrendIndicators.stories.tsx, packages/polaris-viz/src/components/SimpleBarChart/stories/WithTrendIndicators.stories.tsx, packages/polaris-viz/src/components/SimpleBarChart/stories/data.tsx, packages/polaris-viz/src/components/SimpleBarChart/types.ts, packages/polaris-viz/src/components/TrendIndicator/TrendIndicator.tsx, packages/polaris-viz/src/components/TrendIndicator/constants.ts, packages/polaris-viz/src/components/TrendIndicator/index.ts, packages/polaris-viz/src/components/TrendIndicator/stories/meta.tsx, packages/polaris-viz/src/components/TrendIndicator/utilities/estimateTrendIndicatorWidth.ts, packages/polaris-viz/src/components/shared/HorizontalBars/HorizontalBars.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/Label/Label.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/Label/tests/Label.test.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/LabelWrapper/LabelWrapper.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/LabelWrapper/index.ts, packages/polaris-viz/src/components/shared/HorizontalBars/components/index.ts, packages/polaris-viz/src/components/shared/HorizontalBars/tests/HorizontalBars.test.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/utilities/getTrendIndicatorData.ts
Prototyping out inline `<TrendIndicator />` components in `<SimpleBarChart />`/ 
https://6062ad4a2d14cd0021539c1b-hcstxeqycw.chromatic.com/?path=/story/polaris-viz-charts-simplebarchart--with-trend-indicators
=> Inline TrendIndicators

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/stories/WithTrendIndicators.stories.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/HorizontalBars.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/tests/HorizontalBars.test.tsx
Fixed the negative position logic to stop the labels from rendering outside of the chart bounds.
|---|---|
|![image](https://github.com/Shopify/polaris-viz/assets/149873/c2ffc695-5fe3-4b96-80eb-2a568d7c21a9)|![image](https://github.com/Shopify/polaris-viz/assets/149873/b5361777-2ee8-4e32-ae53-02d19997a71e)|
=> Fixed issue with labels bleeding outside of the chart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/TrendIndicator/TrendIndicator.tsx, packages/polaris-viz/src/components/TrendIndicator/components/Svg/Svg.tsx
The `<SVG />` component sets the tab-index property to `0` which was causing the `<TrendIndicator />` component to enter the tab order, even though there's nothing to interact with.
=> Remove tab-index 0 from TrendIndicator svg

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/stories/WithTrendIndicators.stories.tsx, packages/polaris-viz/src/components/SimpleBarChart/utilities.ts, packages/polaris-viz/src/components/TrendIndicator/utilities/estimateTrendIndicatorWidth.ts
We were checking the length of `trend.value` even though it can be `undefined`.
https://6062ad4a2d14cd0021539c1b-mjpmjeklzw.chromatic.com/?path=/story/polaris-viz-charts-simplebarchart--with-trend-indicators
=> Fix undefined value crashing SimpleBarChart

packages/polaris-viz/src/components/FunnelChart/Chart.tsx, packages/polaris-viz/src/components/FunnelChart/FunnelChart.tsx, packages/polaris-viz/src/components/FunnelChart/components/FunnelSegment.tsx, packages/polaris-viz/src/components/FunnelChart/components/Label.scss, packages/polaris-viz/src/components/FunnelChart/components/Label.tsx
This adds the ability to render a Tooltip component from web into the FunnelChart. We pass in an array of objects and use the key from the `data` object to decide which data point Tooltip will render on
[Spin URL](https://admin.web.web-funnel-chart-popover.juwan-petty.us.spin.dev/store/shop1/marketing/reports/tactic?since=2023-06-06&until=2023-07-05&attributionModel=last_click_non_direct&utm_campaign_name=Welcome%20-%20Quiz%3A%20Email%201%20%28WLNMcW%29&utm_campaign_medium=email&referring_channel=klaviyo) where the Tooltip is rendered
=> Add new prop to funnel chart for helper tooltip

packages/polaris-viz-core/src/components/PolarisVizProvider/PolarisVizProvider.tsx, packages/polaris-viz-core/src/contexts/PolarisVizContext.ts, packages/polaris-viz-core/src/index.ts, packages/polaris-viz-core/src/types.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/BarChart.tsx, packages/polaris-viz/src/components/BarChart/stories/Default.stories.tsx, packages/polaris-viz/src/components/ChartContainer/ChartContainer.tsx, packages/polaris-viz/src/components/ChartContainer/components/ChartDimensions/ChartDimensions.tsx, packages/polaris-viz/src/components/ChartErrorBoundary/ChartErrorBoundary.tsx, packages/polaris-viz/src/components/ChartErrorBoundary/tests/ChartErrorBoundary.test.tsx, packages/polaris-viz/src/components/ChartErrorBoundary/utilities/checkForMismatchedData.ts, packages/polaris-viz/src/components/ComboChart/ComboChart.tsx, packages/polaris-viz/src/components/DonutChart/DonutChart.tsx, packages/polaris-viz/src/components/FunnelChart/FunnelChart.tsx, packages/polaris-viz/src/components/LineChart/LineChart.tsx, packages/polaris-viz/src/components/PolarisVizProvider/PolarisVizProvider.tsx, packages/polaris-viz/src/components/SimpleBarChart/SimpleBarChart.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/SimpleNormalizedChart.tsx, packages/polaris-viz/src/components/SparkBarChart/SparkBarChart.tsx, packages/polaris-viz/src/components/SparkLineChart/SparkLineChart.tsx, packages/polaris-viz/src/components/StackedAreaChart/StackedAreaChart.tsx, packages/polaris-viz/src/playground/ErrorBoundary.stories.tsx
Allow consumers to respond to chart errors.
`<PolarisVizProvider />` accepts an `onError` prop. Individual components also have an `onError` prop that will override the context one.
=> Add onError prop to ErrorBoundary

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/TrendIndicator/components/Svg/Svg.scss
Removing the outline when a `<TrendIndicator />` svg has focus.
This one is a little funky to test because storybook removes the outline itself for some reason, so I've attached a screenshot of the element with `focus` state forced on.
This change is only applied to `<TrendIndicator />` so we should be safe to merge into main to test in web.
=> Removed outline from TrendIndicator svg

packages/polaris-viz-core/src/hooks/tests/useYScale.test.tsx, packages/polaris-viz-core/src/hooks/useYScale.ts, packages/polaris-viz-core/src/types.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/Labels/SingleTextLine.tsx, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/stories/FixedYScaleWidth.stories.tsx, packages/polaris-viz/src/components/LineChart/stories/chromatic/FixedYScaleWidth.chromatic.stories.tsx, packages/polaris-viz/src/components/YAxis/YAxis.tsx, packages/polaris-viz/src/utilities/getAxisOptions.ts
Allow consumers to set a fixed width for the yAxis labels
https://6062ad4a2d14cd0021539c1b-zersnikccu.chromatic.com/?path=/story/polaris-viz-charts-linechart--fixed-y-scale-width
=> yAxis Fixed Width

packages/polaris-viz-native/CHANGELOG.md, packages/polaris-viz-native/src/components/SparkLineChart/SparkLineChart.tsx
Fixes an issue where the `theme` prop wasn't being applied to native `<SparkLineChart />`.
|---|---|
|<img width="221" alt="image" src="https://github.com/Shopify/polaris-viz/assets/149873/f8b0d0f2-801a-4df9-8afa-eae9184dc9b2">|<img width="222" alt="image" src="https://github.com/Shopify/polaris-viz/assets/149873/4e7cf412-5a92-48ec-b2c1-229f835607b3">|
https://6062ad4a2d14cd0021539c1b-gwqiiglpim.chromatic.com/?path=/story/polaris-viz-native-charts-sparklinechart--default&args=theme:Light
=> Pass theme down to ChartContainer

packages/polaris-viz-native/CHANGELOG.md, packages/polaris-viz-native/loom.config.ts
This PR fixes the build step for `@shopify/polaris-viz-native`, where the `@shopify/babel-preset` configuration wasn't being correctly applied, thus leading to a `React is not defined` crash when loading some components in React Native.
Ideally, the changes should be applied at the workspace level (it even looks like [we have it set up](https://github.com/Shopify/polaris-viz/blob/eebef89280b19d911d5d5d1dd2951662f0dd82a8/loom.config.ts#L18)), but all the other packages manually apply the configuration, so I thought the RN counterpart should probably follow suit.
| **Before** | **After** |
| ----------- | -------- |
| ![snippet (old)](https://github.com/Shopify/polaris-viz/assets/5504958/6043d83a-4135-40b8-b030-21023f6f1d8e) |  ![snippet](https://github.com/Shopify/polaris-viz/assets/5504958 …
=> Add React 18 setup to Polaris Viz Native

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/components/InnerValue/InnerValue.tsx, packages/polaris-viz/src/components/DonutChart/components/InnerValue/tests/InnerValue.test.tsx
Updates `Donut Chart` to show value of hovered item in the center. 
We want the active value to display as the inner value of the Donut Chart.
See Designs [here](https://www.figma.com/file/lUnNNBLeNTXo8223HRohg5/Smart-viz-updates?type=design&node-id=283-9838&mode=design&t=9wzCshoEsfPOA0qv-0)
https://github.com/Shopify/core-issues/issues/58495
http://localhost:6006/?path=/story/polaris-viz-charts-donutchart--default
=> [Donut Chart] Update center to include value of hovered item

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/stories/playground/ExternalTooltip.stories.tsx, packages/polaris-viz/src/components/LineChart/utilities/getAlteredLineChartPosition.ts, packages/polaris-viz/src/components/LineChart/utilities/tests/getAlteredLineChartPosition.test.ts
Fixed the `y` position of tooltips when performance is impacted.
https://6062ad4a2d14cd0021539c1b-hfmodciywx.chromatic.com/?path=/story/polaris-viz-charts-linechart-playground--external-tooltip
=> Fix performant tooltips rendering at the top of the page

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/StackedAreaChart/components/Area/AnimatedArea.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/Area/Area.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/Area/index.ts, packages/polaris-viz/src/components/StackedAreaChart/components/Area/tests/AnimatedArea.test.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/Area/types.ts, packages/polaris-viz/src/components/StackedAreaChart/components/StackedAreas/StackedAreas.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/StackedAreas/tests/StackedAreas.test.tsx, packages/polaris-viz/src/components/StackedAreaChart/stories/DynamicData.stories.tsx
This PR fixes a bug we are seeing with the stacked area chart throwing when the length of the data changes. After some investigation we found that React spring is unable to animate svgs of different lengths without a custom interpolator but that seemed like overkill for now. Instead I've decided to just not animate when the length of data changes. 
I've updated the Dynamic Data story for the Stacked Area component to change data length as well as value.  
Part of the work for: https://github.com/Shopify/core-issues/issues/59450
🖼 Include screenshots of before and after, if relevant
Before: 
https://github.com/Shopify/polaris-viz/assets/13425309/342fe148-e3b3-442b-ba89-74c2c6a0d5ad
After:
https://github.com/Shopify/polaris-viz/assets/13425309/e06036cc-3239-4f2a-903b-97649de7d581
=> Fix stacked area arity bug

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/stories/chromatic/AllZeroValues.chromatic.stories.tsx, packages/polaris-viz/src/hooks/tests/useDataForHorizontalChart.test.tsx, packages/polaris-viz/src/hooks/useDataForHorizontalChart.ts, packages/polaris-viz/src/hooks/useHorizontalTicksAndScale.ts
We want to render charts with all zero values at the left side of the container instead of the center
Resolves https://github.com/Shopify/core-issues/issues/61609
|---|---|
|![image](https://github.com/Shopify/polaris-viz/assets/149873/c950d96e-14b7-40d6-88e2-13433617287c)|![image](https://github.com/Shopify/polaris-viz/assets/149873/2929cea3-fbe0-4a41-90c4-eb7d3e3537b6)|
https://6062ad4a2d14cd0021539c1b-peipdnhbao.chromatic.com/?path=/story/polaris-viz-chromatic-charts-simplebarchart-allzerovalues--all-zero-values
=> Render all zero charts to left of container

packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/stories/ExternalTooltip.stories.tsx, packages/polaris-viz/src/components/StackedAreaChart/utilities/getAlteredStackedAreaChartPosition.ts, packages/polaris-viz/src/components/StackedAreaChart/utilities/tests/getAlteredStackedAreaChartPosition.test.ts
Fixes: https://github.com/Shopify/core-issues/issues/60331
**Issue**
Received a possible bug that the `ReturningCustomerRate` card was not rendering a tooltip.
- Investigated and found that the tooltip _was_ being rendered, but that when the window was scrolled, the tooltip was rendering outside of the bounds of the chart and was no longer visible. It was also being partially cut off when the scroll value was lower.
https://github.com/Shopify/polaris-viz/assets/33559193/40426d92-6773-4952-b1ad-8458794af3df
- To replicate the issue, staff in to any store and navigate to the Dashboard. Ensure the `ReturningCustomerRate` card is displayed (currently the only StackedArea chart available). 
- If you move this card to a place on the dashboard and have to scroll to access it, hover over and …
=> [Bug Fix]: Adjust tooltip position on StackedAreaChart when page is scrolled

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/constants.ts
We are currently facing an issue in the Customer Cohort Report where some labels are truncated despite having the same number of characters as other labels. This leads to an inconsistent visual experience. This happens because certain numbers are rendered slightly wider than others due to font rendering variations. I'm adding an offset to y-axis labels to fix this issue.
Resolves https://github.com/Shopify/core-issues/issues/62706
| Before | After |
|--------|------|
|<img width="177" alt="Screenshot 2023-11-07 at 10 40 05 AM" src="https://github.com/Shopify/polaris-viz/assets/64446645/87a9b9e0-8463-4608-828a-9996b954613c">|<img width="130" alt="Screenshot 2023-11-07 at 10 40 32 AM" src="https://github.com/Shopify/polaris-viz/assets/64446645/d284314e-2bed-4790-895c-4207ce3904dc">| …
=> Adds an offset to y-axis label in LineChart

packages/polaris-viz-core/src/hooks/useSpringConfig.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/DynamicData.stories.tsx, packages/polaris-viz/src/components/TooltipWrapper/components/TooltipAnimatedContainer.scss, packages/polaris-viz/src/hooks/useBarSpringConfig.ts
BarChart would still have a staggered in animation even when `isAnimated` was `false` because we weren't setting the delay to `0`.
Also fixes the tooltip z-index to match the polaris tooltip.
Resolves https://github.com/Shopify/core-issues/issues/63108
**Before**
https://github.com/Shopify/polaris-viz/assets/149873/f8fb7bd9-aa73-4d5c-bcbc-31f49c45a172
**After**
https://github.com/Shopify/polaris-viz/assets/149873/6f90817f-b879-4fb4-adc6-20ef2e9ccc6d
> [!NOTE]  
> There's an issue where we can't alter the controls in Storybook for some reason that I haven't dug into yet.
=> Remove delay when isAnimated: false. Fix Tooltip z-index

packages/polaris-viz/src/components/LineChartRelational/stories/playground/NoBenchmarkSeries.stories.tsx, packages/polaris-viz/src/utilities/fillMissingDataPoints.ts, packages/polaris-viz/src/utilities/tests/fillMissingDataPoints.test.ts
This fixes an issue that arose when bumping polaris-viz in web.
https://6062ad4a2d14cd0021539c1b-hywmloasex.chromatic.com/?path=/story/polaris-viz-charts-linechartrelational--no-benchmark-series
=> Fix issue with data sets that are empty

.github/workflows/chromatic.yml, packages/polaris-viz-core/src/types.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/utilities/fillMissingDataPoints.ts, packages/polaris-viz/src/utilities/tests/fillMissingDataPoints.test.ts
Allows consumers to customize what value `fillMissingDataPoints` will use to fill missing data. Currently this defaults to `null`.
https://github.com/Shopify/polaris-viz/assets/4960217/dbeddc6b-d498-431d-81aa-24c3bb133e08
Discovered when working on https://github.com/Shopify/core-issues/issues/63824
See video
http://localhost:6006/?path=/story/polaris-viz-charts-linechart--default&args=data[1].isComparison:!undefined;data[1].fillValue:0
=> Introduce optional fillValue property on DataSeries

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/BarChart.tsx, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/LineChart.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/StackedAreaChart.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/VerticalBarChart.tsx
Add enableHideLegendOverflow and renderHiddenLegendLabel props  to Line, VerticalBar, and StackedArea charts. This way we can just turn this feature on for MetricCard vizes. 
I also forgot to pass down the `renderHiddenLegendLabel` prop for the bar and stacked area chart in my previous PR 🙈 
https://6062ad4a2d14cd0021539c1b-udkikcqgza.chromatic.com/
Toggle the `enableHideLegendOverflow` prop for the Line, VerticalBar, and StackedArea charts.
=> Add enableHideLegendOverflow and renderHiddenLegendLabel props

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/tests/Chart.test.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/Label/Label.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/components/Label/tests/Label.test.tsx
The `<Label>` component for HorizontalBars currently uses a `<foreignObject>` to render its text. In some rare situations, the browser "disagrees" with what we've computed as the explicit width and height of the element and causes text to wrap to a second line that's outside the bounds of the `<foreignObject>` and therefore invisible. 
<details><summary>Example:</summary>
https://github.com/Shopify/polaris-viz/assets/4888172/dead1393-f074-42ee-a90b-6cf4d8832e80
</details>
Letters that descend below the line of text, such as "g" or "j," were also clipped if their edges extend past the bounds of the `<foreignObject>`:
This PR replaces the `<foreignObject>` + `<div>` combo with a plain SVG `<text>` element to eliminate the chance of wrapping. Horizontal bar chart bar labels should have the …
=> Switch HorizontalBars label from foreignObject to SVG text element

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/BarChart.tsx, packages/polaris-viz/src/components/ChartContainer/ChartContainer.tsx, packages/polaris-viz/src/components/ComboChart/ComboChart.tsx, packages/polaris-viz/src/components/DonutChart/DonutChart.tsx, packages/polaris-viz/src/components/FunnelChart/FunnelChart.tsx, packages/polaris-viz/src/components/SimpleBarChart/SimpleBarChart.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/SimpleNormalizedChart.tsx, packages/polaris-viz/src/components/SparkBarChart/SparkBarChart.tsx, packages/polaris-viz/src/components/SparkLineChart/SparkLineChart.tsx, packages/polaris-viz/src/components/StackedAreaChart/StackedAreaChart.tsx, packages/polaris-viz/src/hooks/ColorVisionA11y/stories/Playground.tsx
While working on https://github.com/Shopify/core-issues/issues/67182 I noticed that we weren't passing the `id` down to all the charts correctly.
=> Pass id down to all charts

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/HorizontalStacked.stories.tsx, packages/polaris-viz/src/components/shared/HorizontalStackedBars/HorizontalStackedBars.tsx, packages/polaris-viz/src/constants.ts
Fixed the positioning of the `<ZeroLine />` for the Stacked Horizontal Chart when all values are negative.
N/A
| Before | After |
|--------|------|
|<img width="1093" alt="Screenshot 2024-02-26 at 8 11 58 AM" src="https://github.com/Shopify/polaris-viz/assets/64446645/203960fe-d0e1-4228-95d2-f3910100b883">|<img width="832" alt="Screenshot 2024-02-26 at 8 36 55 AM" src="https://github.com/Shopify/polaris-viz/assets/64446645/26210d6a-f862-43cf-b47d-786263c6cc3e">|
https://6062ad4a2d14cd0021539c1b-yzbjqfmezj.chromatic.com/?path=/story/polaris-viz-charts-barchart--horizontal-stacked
=> Fix positioning of zero line when all negative values

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/hooks/index.ts, packages/polaris-viz/src/hooks/tests/useWatchActiveSeries.test.tsx, packages/polaris-viz/src/hooks/useWatchActiveSeries.ts, packages/polaris-viz/src/index.ts
Allows a consumer to conditionally watch for events. If for some reason the `id` prop is not available, we won't attach the events to window.
=> Allow id to be null

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleNormalizedChart/Chart.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/SimpleNormalizedChart.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/stories/FormattedValues.stories.tsx
In order to fix https://github.com/Shopify/core-issues/issues/68614 & https://github.com/Shopify/core-issues/issues/68845 we need to be able to format the name differently than the data we provide to `polaris-viz`.
https://6062ad4a2d14cd0021539c1b-xgegmpkewo.chromatic.com/?path=/story/polaris-viz-charts-simplenormalizedchart--formatted-values
=> Added seriesNameFormatter to SimpleNormalizedChart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/DonutChart/components/LegendValues/LegendValues.scss, packages/polaris-viz/src/components/DonutChart/components/LegendValues/LegendValues.tsx, packages/polaris-viz/src/components/DonutChart/components/LegendValues/components/LegendValueItem/LegendValueItem.scss, packages/polaris-viz/src/components/DonutChart/components/LegendValues/components/LegendValueItem/LegendValueItem.tsx, packages/polaris-viz/src/components/DonutChart/stories/DonutChart.chromatic.stories.tsx, packages/polaris-viz/src/components/DonutChart/stories/TruncatedLegends.stories.tsx, packages/polaris-viz/src/components/Legend/components/LegendItem/LegendItem.tsx
Limit the `DonutChart` legends from taking up more than 50% of the chart space.
https://github.com/Shopify/core-issues/issues/68612
https://6062ad4a2d14cd0021539c1b-xydvmesepk.chromatic.com/?path=/story/polaris-viz-charts-donutchart--truncated-legends
=> Limit Donut legend to 50% of chart width

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/DonutChart/DonutChart.tsx, packages/polaris-viz/src/components/DonutChart/components/LegendValues/LegendValues.tsx, packages/polaris-viz/src/components/DonutChart/components/LegendValues/components/LegendValueItem/LegendValueItem.tsx, packages/polaris-viz/src/components/DonutChart/stories/FormattedValues.stories.tsx, packages/polaris-viz/src/components/LegendContainer/hooks/useLegend.ts
We want to be able to react to raw values in web, so we need to add a method to format the values after we're used it.
Resolves https://github.com/Shopify/core-issues/issues/69052
https://6062ad4a2d14cd0021539c1b-ofyhfkvzly.chromatic.com/?path=/story/polaris-viz-charts-donutchart--formatted-values
=> Add seriesNameFormatter to DonutChart

packages/polaris-viz-core/src/hooks/tests/useTheme.test.tsx, packages/polaris-viz-core/src/hooks/useTheme.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/BarChart.chromatic.stories.tsx
Previously we threw an error when a theme could not be found, but that would cause the parent component to crash.
Now we'll return the default theme and warn in the console instead of an `Error`.
Resolves https://github.com/Shopify/polaris-viz/issues/1659
https://6062ad4a2d14cd0021539c1b-dhhtmrpotq.chromatic.com/?path=/story/polaris-viz-charts-barchart-chromatic--bad-theme
=> Return default theme when unknown theme value is passed

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/index.ts
When I exported  the `fillMissingDataPoint` utility, I forgot to export it in the `packages/polaris-viz/src/index.ts`
=> Re-export fillMissingDataPoints

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChartRelational/LineChartRelational.tsx, packages/polaris-viz/src/components/LineChartRelational/components/RelatedAreas/RelatedAreas.tsx, packages/polaris-viz/src/components/LineChartRelational/stories/playground/SwitchingMetrics.stories.tsx
Remount `<RelatedAreas />` when the data changes.
Resolves https://github.com/Shopify/core-issues/issues/71032#issuecomment-2129763962
=> Remount RelatedAreas when data changes

packages/polaris-viz-core/src/constants.ts, packages/polaris-viz-core/src/styles/shared/_variables.scss, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/chromatic/components/StorySection.tsx, packages/polaris-viz/src/components/shared/HorizontalBars/HorizontalBars.tsx, tests/setup/tests.ts
Updating the `TrendIndicator` colors and removing the comparison color on `SimpleBarChart` labels.
Resolves https://github.com/Shopify/core-issues/issues/71943
Resolves https://github.com/Shopify/core-issues/issues/72400
Resolves https://github.com/Shopify/core-issues/issues/72398
Resolves https://github.com/Shopify/core-issues/issues/70886
TrendIndicators: https://6062ad4a2d14cd0021539c1b-kwhnbhyroc.chromatic.com/?path=/story/chromatic-components--trendindicator
Comparion Labels: https://6062ad4a2d14cd0021539c1b-kwhnbhyroc.chromatic.com/?path=/story/polaris-viz-charts-simplebarchart--comparison
=> Update TrendIndicator colors. Remove comparison label color

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/utilities.ts, packages/polaris-viz/src/components/TrendIndicator/TrendIndicator.tsx, packages/polaris-viz/src/components/TrendIndicator/utilities/estimateTrendIndicatorWidth.ts, packages/polaris-viz/src/utilities/getTrendIndicatorData.ts
Resolves https://github.com/Shopify/core-issues/issues/72470
https://6062ad4a2d14cd0021539c1b-kviftasjjp.chromatic.com/?path=/story/polaris-viz-subcomponents-trendindicator--default
=> Bump TrendIndicator font weight to 650

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/DonutChart/components/LegendValues/LegendValues.tsx, packages/polaris-viz/src/components/LegendContainer/LegendContainer.tsx, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/LineChart.tsx
Part of: https://github.com/Shopify/core-issues/issues/73397
- Updates Donut Chart table legend width to only take up required space
- This PR also adds a `hideOverflowLegend` prop to the LIne Chart to be able to opt in and out of that behaviour 
https://6062ad4a2d14cd0021539c1b-jnckoierdc.chromatic.com/
=> Add overflow legend prop and update Donut Chart legend width

packages/polaris-viz-core/CHANGELOG.md, packages/polaris-viz-core/src/constants.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/Annotations/components/AnnotationContent/AnnotationContent.scss, packages/polaris-viz/src/components/ChartSkeleton/components/DonutSkeleton/DonutSkeleton.scss, packages/polaris-viz/src/components/Legend/components/LegendItem/LegendItem.scss, packages/polaris-viz/src/components/LegendContainer/components/HiddenLegendTooltip.scss, packages/polaris-viz/src/components/SimpleNormalizedChart/SimpleNormalizedChart.scss, packages/polaris-viz/src/components/TooltipContent/components/TooltipRow/TooltipRow.scss, packages/polaris-viz/src/components/TooltipContent/components/TooltipTitle/TooltipTitle.scss, packages/polaris-viz/src/components/shared/Label/tests/Label.test.tsx
Follow up of https://github.com/Shopify/polaris-viz
- Change font size for legends, labels, and tooltips to 11px
- Remove focus state onClick in `LegendItem` (should still be visible for keyboard interaction)
|---|---|
| ![image](https://github.com/user-attachments/assets/45eef2b6-5494-4a00-b587-b4cba03deba2)  | ![image](https://github.com/user-attachments/assets/25448ef5-ad24-4ed7-8622-f421ee37a117) |
https://6062ad4a2d14cd0021539c1b-yrsertjuva.chromatic.com/?path=/story/intro--page
* Confirm the body text in legends, tooltips, annotations, axis labels, etc are 11px
* Confirm you do not see the blue outline focus state when clicking on a legend item, but you can see it when focusing on it via keyboard
=> Legend styling changes

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/DonutChart/DonutChart.scss, packages/polaris-viz/src/components/DonutChart/components/InnerValue/InnerValue.tsx, packages/polaris-viz/src/components/DonutChart/components/InnerValue/tests/InnerValue.test.tsx, packages/polaris-viz/src/components/DonutChart/stories/TruncatedLegends.stories.tsx
The inner value content font size in the donut chart was set to a static value, which led to this value not being scaled with the donut size. Now, we calculate the font size based on the donut diameter.
Related https://github.com/Shopify/core-issues/issues/74510
| Before | After |
|--------|------|
|<img width="331" alt="Screenshot 2024-07-31 at 6 58 49 PM" src="https://github.com/user-attachments/assets/f9340deb-65cd-4005-9f6e-497723026026">|<img width="207" alt="Screenshot 2024-07-31 at 6 59 05 PM" src="https://github.com/user-attachments/assets/3d6057ee-0f47-49d8-8430-5d6d167b45a1">|
[🎩  Small donut](https://6062ad4a2d14cd0021539c1b-fiwbylwivc.chromatic.com/?path=/story/polaris-viz-charts-donutchart--truncated-legends)
[🎩  Medium …
=> Calculate inner content value font size based on donut diameter

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/DonutChart/components/InnerValue/InnerValue.tsx, packages/polaris-viz/src/components/DonutChart/stories/EmptyState.stories.tsx, packages/polaris-viz/src/components/DonutChart/tests/DonutChart.test.tsx, packages/polaris-viz/src/types.ts
- Updates empty state to show when all values are zero
- This PR also extends the `RenderInnerValueContent` type to include `dimensions`, this will be useful for the consumer to dynamically changing the size of the inner value based on the size of the chart container
https://6062ad4a2d14cd0021539c1b-rkoidmddvx.chromatic.com/
=> [Donut chart] Show empty state when all values are zero

packages/polaris-viz-core/src/components/LineSeries/LineSeries.tsx, packages/polaris-viz-core/src/components/LineSeries/tests/LineSeries.test.tsx, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/stories/WithNullValues.stories.tsx
We have cases in the comparison data array where one non-null value is followed by a null value; this point is not rendered on the screen because the size of the dash stroke is too small. In order for the comparison line to be visualized on the screen, we need to have at least two consecutive non-null values or set the stroke to "none." My approach to fix it is to render these values as individual standing points instead of as a part of the line.
No
Before:
https://github.com/user-attachments/assets/0593cad8-5db5-431b-8679-6ab86ace67a3
After:
https://github.com/user-attachments/assets/b83735b4-7887-4505-a67a-4e33d0c7843d
[Storybook](https://6062ad4a2d14cd0021539c1b-zzykkiadxr.chromatic.com/?path=/story/polaris-viz-charts-linechart--with-null-values)
- Make sure the standalone values in …
=> Render single data point values for comparison line chart

packages/polaris-viz-core/src/contexts/ChartContext.tsx, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/BarChart.tsx, packages/polaris-viz/src/components/BarChart/stories/playground/ExternalTooltip.stories.tsx, packages/polaris-viz/src/components/ChartContainer/ChartContainer.tsx, packages/polaris-viz/src/components/ChartContainer/components/ChartDimensions/ChartDimensions.tsx, packages/polaris-viz/src/components/LineChart/LineChart.tsx, packages/polaris-viz/src/components/LineChart/stories/playground/ExternalTooltip.stories.tsx, packages/polaris-viz/src/components/LineChart/utilities/getAlteredLineChartPosition.ts, packages/polaris-viz/src/components/StackedAreaChart/StackedAreaChart.tsx, packages/polaris-viz/src/components/StackedAreaChart/stories/playground/ExternalTooltipPortal.stories.tsx, packages/polaris-viz/src/components/TooltipWrapper/TooltipWrapper.tsx, packages/polaris-viz/src/components/TooltipWrapper/components/TooltipAnimatedContainer.tsx, packages/polaris-viz/src/components/TooltipWrapper/utilities.ts
Now that `web` renders the page inside of a `<Frame />` component, we don't have access to the `window` object to get scroll values.
We need to target that element directly so we're going to accept a `scrollContainer` prop that will accept the frames DOM node so we can correctly position tooltips.
Resolves https://github.com/Shopify/core-issues/issues/76538
Spin: https://admin.web.table-text.matthew-vickers.us.spin.dev/store/shop1/analytics
- [BarChart](https://6062ad4a2d14cd0021539c1b-zfywbkjnnm.chromatic.com/iframe.html?args=&id=polaris-viz-charts-barchart-playground--external-tooltip-with-frame&viewMode=story)
- [LineChart](https://6062ad4a2d14cd0021539c1b-zfywbkjnnm.chromatic.com/iframe.html?args=&id=polaris-viz-charts-linechart-playground--external-tooltip-with-frame&viewMode=story) …
=> Add scrollContainer prop to charts that use portal for tooltips

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/Annotations/Annotations.tsx, packages/polaris-viz/src/components/Annotations/hooks/tests/useAnnotationPositions.test.tsx, packages/polaris-viz/src/components/Annotations/hooks/useAnnotationPositions.ts, packages/polaris-viz/src/components/Annotations/tests/Annotations.test.tsx, packages/polaris-viz/src/components/ComboChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/stories/Annotations.stories.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx
Format `<Annotation />` keys with the xAxis formatter so that the keys provided and keys displayed are the same and don't rely on the raw data.
=> Format annotation keys

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/StackedAreaChart/hooks/useStackedChartTooltipContent.ts, packages/polaris-viz/src/components/StackedAreaChart/stories/playground/LongerComparison.stories.tsx, packages/polaris-viz/src/utilities/getStackedValues.ts
Fixes and issue where data series with different lengths would cause the `StackedAreaChart` to crash because it was looking for points that didn't exist.
https://6062ad4a2d14cd0021539c1b-xzoptwehfg.chromatic.com/?path=/story/polaris-viz-charts-stackedareachart-playground--longer-comparison
This story should not crash
=> Allow different series length in StackedAreaChart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/Chart.tsx, packages/polaris-viz/src/components/SimpleBarChart/stories/playground/SkinnyTrend.stories.tsx, packages/polaris-viz/src/components/SimpleBarChart/tests/utilities.test.ts, packages/polaris-viz/src/components/SimpleBarChart/utilities.ts, packages/polaris-viz/src/hooks/tests/useDataForHorizontalChart.test.tsx, packages/polaris-viz/src/hooks/useDataForHorizontalChart.ts
When building the width offset values for trends, we were originally trying to associate a trend with the longest value in each series.
This broke down when a series contained a value that was longer than the series that contained the trend.
Now we're going to find the longest trend for each positive and negative side of the chart and use those values.
https://github.com/Shopify/core-issues/issues/77311
|---|---|
|![image](https://github.com/user-attachments/assets/a0d7f2e5-e0f4-4be0-8821-10d2bad51996)|![image](https://github.com/user-attachments/assets/3e5b3dc5-6c4c-4d8b-b931-579cbed05801)|
=> Change logic around trend indicator width offset

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx
Fixes this broken chart we saw on Sidekick this morning, which results from us passing the chart a value of Infinity
Using the existing error handling in the chart, we can just make the chart show the error state. An error will be thrown, so we should see these errors in bugsnag if the consuming project surfaces them.
Note: I spent a while trying to add a test for this but had issues checking for the error. Please let me know if you have any ideas!
Resolves https://github.com/Shopify/web/issues/144056
|---|---|
| <img width="556" alt="Screenshot 2024-10-10 at 2 59 49 PM" src="https://github.com/user-attachments/assets/db769849-e3cb-491a-a7b6-be2f974149f7">  | <img width="547" alt="Screenshot 2024-10-10 at 2 59 36 PM" …
=> Show error state when chart contains infinity

packages/polaris-viz/src/components/BarChart/stories/playground/ExternalTooltip.stories.tsx, packages/polaris-viz/src/components/ChartContainer/ChartContainer.tsx, packages/polaris-viz/src/components/ChartContainer/components/ChartDimensions/ChartDimensions.tsx
We were only updating the dimensions on `resize`, so `dimensions.x` and `dimensions.y` were outdated when we were trying to calculate the tooltip position [here](https://github.com/Shopify/polaris-viz/blob/main/packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx#L391-L392).
In this PR, we added a `onMouseEnter` and `onFocusIn`  handler to also update the dimensions when you interact with the chart.  
Fix https://github.com/Shopify/core-issues/issues/78973
Before:
https://github.com/user-attachments/assets/7f881726-54ef-45c1-aa6d-3a8634ced5d0
After:
https://github.com/user-attachments/assets/232f1c24-0355-4d1d-bfd0-8c30a6c47516
Toggle the top/left margins and make sure the tooltips are in the correct position.
Test with scrolling as well. …
=> Check chart bounds when mouse enters chart

packages/polaris-viz-core/src/hooks/useSparkBar.ts, packages/polaris-viz-core/src/hooks/useSparkLine.ts, packages/polaris-viz-core/src/hooks/useYScale.ts, packages/polaris-viz-core/src/index.ts, packages/polaris-viz-core/src/utilities/index.ts, packages/polaris-viz-core/src/utilities/isInfinity.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/ComboChart/hooks/useDualAxisTicks.ts, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/FunnelChart/Chart.tsx, packages/polaris-viz/src/components/SimpleNormalizedChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/hooks/useDataForHorizontalChart.ts
Fixes too broad infinite check
`Number.isFinite` would return false for `NaN`, `null` and empty values. We really only wanted to check for `Infinity` and `-Infinity`.
=> Tweak infinite check

packages/polaris-viz/src/components/Grid/Grid.scss, packages/polaris-viz/src/components/Grid/Grid.tsx, packages/polaris-viz/src/components/Grid/components/GridBackground.tsx, packages/polaris-viz/src/components/Grid/components/GroupCell.tsx, packages/polaris-viz/src/components/Grid/stories/ResizeableChart.stories.tsx, packages/polaris-viz/src/components/Grid/tests/GroupCell.test.tsx, packages/polaris-viz/src/components/Grid/utilities/constants.ts
This PR fix the responsiveness of the chart `Grid`. This visualization is going to be used in `RFM analysis`.
Designs: [Link](https://www.figma.com/design/ADgpIRzImXVud8ngDgonDk/RFM-analysis?node-id=2964-88879&node-type=section&m=dev) 
[Link](https://g6lzjwjtzcjc5evv.tunnel.shopifycloud.tech/?path=/docs/polaris-viz-charts-grid--default)
=> passanelli, Fix Grid chart responsiveness issues and hide Labels on small heights

packages/polaris-viz/src/components/Grid/components/GroupCell.scss, packages/polaris-viz/src/components/Grid/components/GroupInfo.tsx, packages/polaris-viz/src/components/Grid/tests/Grid.test.tsx, packages/polaris-viz/src/components/Grid/utilities/constants.ts, packages/polaris-viz/src/components/Grid/utilities/truncate-text.ts
Improves Grid chart labels and values to truncate when overflow containers through the `truncateText` utility function.
Update css to remove outline on Grid groups.
Increase Y_LABEL_OFFSET to put yLabel closer to the left edge of the chart container
Tophat 🎩  [link](https://a0p2bxxxziittdvf.tunnel.shopifycloud.tech/?path=/story/polaris-viz-charts-grid--resizeable-chart)
Not sure why is not visible but there is a resizable container which you can play around:
https://github.com/user-attachments/assets/c02ee2e6-982c-416e-bf44-abaa6ab5b898
=> feature, Improves Grid chart labels and values responsivenes

packages/polaris-viz-core/src/constants.ts, packages/polaris-viz/CHANGELOG.md
Based on feedback in https://github.com/Shopify/web/pull/148498#pullrequestreview-2443648407 we want to change the touch font size to `12px`.
Before we reverted, it was `14px`. @pabmtl and I decided that `12px` should address the sizing issues.
https://6062ad4a2d14cd0021539c1b-zxnowkgpzy.chromatic.com/
=> Change touch font size to 12px

packages/polaris-viz/src/components/Grid/Grid.tsx, packages/polaris-viz/src/components/Grid/components/Arrows.scss, packages/polaris-viz/src/components/Grid/components/Arrows.tsx, packages/polaris-viz/src/components/Grid/components/Tooltip.scss, packages/polaris-viz/src/components/Grid/components/Tooltip.tsx, packages/polaris-viz/src/components/Grid/stories/data.tsx, packages/polaris-viz/src/components/Grid/types.ts, packages/polaris-viz/src/components/Grid/utilities/constants.ts
This PR adds support for the feedback received from Glen and Cynthia during OK2 session.
- Add support to show CTAs buttons on tooltips when available
- Deselect groups when clicking outside Grid chart
Ticket https://github.com/orgs/Shopify/projects/10349/views/1?pane=issue&itemId=88576072&issue=Shopify%7Crfm-pipeline%7C126
Tophat link [url](https://xjyz8qsb3hrrmjnx.tunnel.shopifycloud.tech/?path=/story/polaris-viz-charts-grid--default)
=> feature, Add support to show CTAs button on group tooltips

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/components/LegendValues/LegendValues.tsx, packages/polaris-viz/src/components/DonutChart/components/LegendValues/components/LegendValueItem/LegendValueItem.tsx, packages/polaris-viz/src/components/DonutChart/tests/DonutChart.test.tsx, packages/polaris-viz/src/components/LegendContainer/components/HiddenLegendTooltip.tsx, packages/polaris-viz/src/components/LegendContainer/tests/LegendsContainer.test.tsx, packages/polaris-viz/src/components/SparkLineChart/tests/Chart.test.tsx, packages/polaris-viz/src/components/TooltipContent/hooks/tests/useGetLongestLabelFromData.test.tsx, packages/polaris-viz/src/hooks/ColorVisionA11y/tests/useWatchColorVisionEvents.test.tsx, packages/polaris-viz/src/hooks/tests/useLinearChartAnimations.test.tsx, packages/polaris-viz/src/hooks/useLinearChartAnimations.tsx, tests/setup/tests.ts
We were running `seriesNameFormatter` multiple times on a `<Legend />` in the `<DonutChart />` component.
This is causing issues in web because the `i18n.translate` function is running the second time on a formatted value, which throws a bugsnag error.
|---|---|
|![image](https://github.com/user-attachments/assets/44e7eb46-d4c2-40c0-af5a-1ec0975635cc)|![image](https://github.com/user-attachments/assets/d8dc033a-36b8-4900-bc64-56b9920c6e2f)|
=> Fix issue where legends would get formatted twice

packages/polaris-viz-core/src/types.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/Annotations/components/AnnotationLabel/AnnotationLabel.test.tsx, packages/polaris-viz/src/components/Annotations/components/AnnotationLabel/AnnotationLabel.tsx, packages/polaris-viz/src/components/Labels/SingleTextLine.tsx, packages/polaris-viz/src/components/Legend/components/LegendItem/LegendItem.tsx, packages/polaris-viz/src/components/Legend/components/LegendItem/test/LegendItem.test.tsx, packages/polaris-viz/src/components/LineChartRelational/components/CustomLegend/CustomLegend.tsx, packages/polaris-viz/src/components/LineChartRelational/components/CustomLegend/tests/CustomLegend.test.tsx, packages/polaris-viz/src/components/LineChartRelational/stories/data.tsx, packages/polaris-viz/src/components/LinePreview/LinePreview.tsx, packages/polaris-viz/src/components/LinePreview/tests/LinePreview.test.tsx, packages/polaris-viz/src/components/TooltipContent/components/TooltipRow/TooltipRow.tsx, packages/polaris-viz/src/components/YAxis/YAxis.tsx, packages/polaris-viz/src/components/shared/SeriesIcon/SeriesIcon.test.tsx, packages/polaris-viz/src/components/shared/SeriesIcon/SeriesIcon.tsx, packages/polaris-viz/src/constants.ts
1. We need to add support for showing a dashed line in the legend. The use case is for benchmarks where the `Median` line is dashed, so the legend should follow the same pattern.
2. Fixed Annotations textAnchor property, it shouldn't be `left` `middle` `right` but `start` `middle` `end`
3. Fix text alignment on annotations: Should be centered
Before:
After:
🎩  Tophatting:
1. Annotations text alignment: https://x5mqehaaczjinobf.tunnel.shopifycloud.tech/?path=/story/polaris-viz-charts-linechart--annotations
2. Dashed legend in line chart relational: https://x5mqehaaczjinobf.tunnel.shopifycloud.tech/?path=/story/polaris-viz-charts-linechartrelational--default
=> Add dashed support for legends

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/LineChart/stories/playground/ExternalTooltip.stories.tsx, packages/polaris-viz/src/components/TooltipWrapper/TooltipWrapper.tsx, packages/polaris-viz/src/components/TooltipWrapper/utilities/eventPoint.ts, packages/polaris-viz/src/components/TooltipWrapper/utilities/getAlteredLineChartPosition.ts, packages/polaris-viz/src/components/TooltipWrapper/utilities/getLineChartTooltipPosition.ts, packages/polaris-viz/src/components/TooltipWrapper/utilities/tests/getAlteredLineChartPosition.test.ts
We weren't using the `containerBounds.y` value when position the tooltip in `LineCharts` while tabbing through the points so the tooltip was misaligned.
=> Fix mis-positioned LineChart tooltips while tabbing points

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/VerticalBarChart/components/VerticalBar/VerticalBar.tsx
Improve the bar animation when the value changes from negative to positive for vice versa 
Resolves https://github.com/Shopify/core-issues/issues/81906
|---|---|
|<video src="https://github.com/user-attachments/assets/4c221ef6-f180-48ce-828d-e17ee8d20471" />|  <video src="https://github.com/user-attachments/assets/50603191-8989-44e5-8038-3ed045fe0931" />|
https://6062ad4a2d14cd0021539c1b-kipahzvwhw.chromatic.com/?path=/story/polaris-viz-charts-barchart--default
Note: I removed these changes in Storybook so they aren't on the PR
=> Fix bar chart animation when sign changes

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/TooltipWrapper/utilities/getAlteredVerticalBarPosition.ts
Place the tooltip for vertical `BarChart` above the chart on mobile so that the tooltip isn't displayed under the users thumb/finger.
Resolves https://github.com/Shopify/core-issues/issues/82177
https://github.com/user-attachments/assets/c459a3fd-aeab-4df9-b8ae-4b721107b22c
https://6062ad4a2d14cd0021539c1b-crdjmhwkgw.chromatic.com/iframe.html?args=&id=polaris-viz-charts-barchart-playground--external-tooltip&viewMode=story
=> Place tooltip above chart on mobile

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/components/LegendValues/LegendValues.tsx, packages/polaris-viz/src/components/DonutChart/components/LegendValues/tests/LegendValues.test.tsx
Fixes double formatting and inaccurate measuring in the Donut Chart
Should fix https://github.com/Shopify/web/issues/152100 once updated in web
You can see below in the console that the string we were measuring double formatted the label. You can see that as a result, the container was larger than it needed to be.
After, the container is the correct size, and you can see in the console that the string being measured is not double formatted.
|---|---|
| <img width="1202" alt="Screenshot 2024-12-20 at 9 25 50 AM" src="https://github.com/user-attachments/assets/705cd84f-364e-4019-ac1c-7e077e570ae2" />|  <img width="1197" alt="Screenshot 2024-12-20 at 9 26 28 AM" src="https://github.com/user-attachments/assets/cf194ea7-4174-4992-b08b-f0f1c984d557" /> |
I haven't added a …
=> Stop double formatting in label calculation

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/StackedAreaChart/components/StackedAreas/StackedAreas.tsx, packages/polaris-viz/src/components/StackedAreaChart/components/StackedAreas/tests/StackedAreas.test.tsx
https://github.com/Shopify/web/issues/152053
The change in https://github.com/Shopify/polaris-viz/pull/1766 fixed a bug with our stacked area charts but introduced a regression to a bug that was previously fixed in https://github.com/Shopify/polaris-viz/pull/1578
The TLDR of the `The arity of each "output" value must be equal` bug was:
>React spring is unable to animate svgs of different lengths without a custom interpolator but that seemed like overkill for now. Instead I've decided to just not animate when the length of data changes
This PR removes the animation when the series length changes. I had previously re-enabled this animation while fixing another issue, not understanding why it was disabled, now I know 😄 
Storybook: https://6062ad4a2d14cd0021539c1b-yivymlsivd.chromatic.com/?pat …
=> Fix stacked area arity bug regression

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/SimpleBarChart/stories/playground/NoTrendTight.stories.tsx, packages/polaris-viz/src/components/SimpleBarChart/utilities.ts, packages/polaris-viz/src/components/TrendIndicator/index.ts
We were not accounting to trends that render a `—` when calculating the width of the element so it was coming back as `0`. This caused the trend to render outside the bounds of the SVG.
https://github.com/Shopify/core-issues/issues/83173
|---|---|
|![image](https://github.com/user-attachments/assets/3781c514-8391-4bc7-8123-2250f814235d)|![image](https://github.com/user-attachments/assets/63d090ab-dd97-4473-bb85-1f85fed2f23f)|
https://6062ad4a2d14cd0021539c1b-cepylwphgr.chromatic.com/?path=/story/polaris-viz-charts-simplebarchart-playground--no-trend-tight
=> Fix issue where trend indicator would render outside chart bounds

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DefaultPreview/DefaultPreview.scss, packages/polaris-viz/src/components/DefaultPreview/DefaultPreview.tsx, packages/polaris-viz/src/components/DefaultPreview/index.ts, packages/polaris-viz/src/components/DefaultPreview/stories/DefaultPreview.stories.tsx, packages/polaris-viz/src/components/DefaultPreview/stories/data.tsx, packages/polaris-viz/src/components/DefaultPreview/stories/meta.tsx, packages/polaris-viz/src/components/DefaultPreview/tests/DefaultPreview.test.tsx, packages/polaris-viz/src/components/Legend/components/LegendItem/LegendItem.scss, packages/polaris-viz/src/components/Legend/constants.ts, packages/polaris-viz/src/components/index.ts, packages/polaris-viz/src/components/shared/SeriesIcon/SeriesIcon.test.tsx, packages/polaris-viz/src/components/shared/SeriesIcon/SeriesIcon.tsx
As part of https://github.com/Shopify/analytics-ui-components/pull/322 we want to change the default series icon to a circle instead of a rounded square.
[Figma](https://www.figma.com/design/UZQSiau68Wh6TbsEowanTH/Visualizations-%2B-Tooltips?node-id=1167-3610&p=f&t=oBAJZkIwWJ71fGv3-0)
=> Change default series icon shape to circle

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/FunnelChartNext/Chart.tsx, packages/polaris-viz/src/components/FunnelChartNext/components/Tooltip/Tooltip.scss, packages/polaris-viz/src/components/FunnelChartNext/constants.ts
We found a small discrepancy in https://github.com/Shopify/analytics-ui-components/pull/471 when viewing the funnel tooltips in web. Because we were not setting an explicit `line-height` in the Funnel tooltips, they were being inherited from web which was causing them to appear larger than desired. This PR just explicitly sets the `line-height` in the tooltip
https://6062ad4a2d14cd0021539c1b-xtlgbpdvug.chromatic.com/?path=/story/polaris-viz-charts-funnelchartnext--with-trend-indicators
=> Funnel tooltip - explicitly set line height

packages/polaris-viz/src/components/BarChart/BarChart.tsx
…them
Data points with keys like 'Product · January 1' sometimes fail to parse as a Date, meaning that the data is not correctly backfilled and comparison bars are not matched up correctly to primary bars.
Before this fix:
After this fix:
Notice that bars with concatenated date strings for comparisons are correctly grouped with their corresponding primary bar.
part of https://github.com/Shopify/core-issues/issues/84103
=> fix validation of dates in BarChart to correctly fill missing data for concatenated string keys

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/Annotations/Annotations.tsx, packages/polaris-viz/src/components/Annotations/components/AnnotationContent/AnnotationContent.scss, packages/polaris-viz/src/components/Annotations/components/AnnotationContent/AnnotationContent.test.tsx, packages/polaris-viz/src/components/Annotations/components/AnnotationContent/AnnotationContent.tsx, packages/polaris-viz/src/components/Annotations/tests/Annotations.test.tsx, packages/polaris-viz/src/components/BarChart/BarChart.tsx, packages/polaris-viz/src/components/ComboChart/Chart.tsx, packages/polaris-viz/src/components/ComboChart/ComboChart.tsx, packages/polaris-viz/src/components/DonutChart/DonutChart.tsx, packages/polaris-viz/src/components/HorizontalBarChart/Chart.tsx, packages/polaris-viz/src/components/HorizontalBarChart/HorizontalBarChart.tsx, packages/polaris-viz/src/components/HorizontalBarChart/components/HorizontalBarChartXAnnotations/HorizontalBarChartXAnnotations.tsx, packages/polaris-viz/src/components/HorizontalBarChart/components/HorizontalBarChartYAnnotations/HorizontalBarChartYAnnotations.tsx, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/LineChart.tsx, packages/polaris-viz/src/components/LineChart/stories/Annotations.stories.tsx, packages/polaris-viz/src/components/LineChart/tests/Chart.test.tsx, packages/polaris-viz/src/components/LineChartPredictive/LineChartPredictive.tsx, packages/polaris-viz/src/components/LineChartRelational/LineChartRelational.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/StackedAreaChart.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/polaris-viz/src/types.ts
In order to display custom annotations for an upcoming report, looking to provide support to render more than just a `string` within the annotations popover. Allowing for more dynamism and flexibility in how we represent data and annotations. This was the recommended approach discussing in Slack, and UX was also looking to gain this functionality.
Includes adding a `renderAnnotationContent` prop for all charts that support annotations (some don't seem to). I've split the commits so that the initial commit is adding the code for this, along with one usage for LineChart.
Relates to https://github.com/Shopify/temp-project-mover-Archetypically-20250318093910/issues/239
|---|---|
|<img width="1512" alt="image" src="https://github.com/user-attachments/assets/2165b85c-c401-4e …
=> Add Support for Dynamic Annotation Popover Rendering

packages/polaris-viz-core/src/constants.ts, packages/polaris-viz-core/src/types.ts, packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/VerticalBarChart/hooks/tests/useXScale.test.tsx, packages/polaris-viz/src/components/VerticalBarChart/hooks/useVerticalBarChart.ts, packages/polaris-viz/src/components/VerticalBarChart/hooks/useXScale.ts
Allows the spacing to be changed by setting the `bar.gap` theme value.
Resolves https://github.com/shop/issues-analytics/issues/1353
=> Allow gap between bars to be overridden

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/BarChart/BarChart.tsx, packages/polaris-viz/src/components/BarChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/DonutChart/DonutChart.tsx, packages/polaris-viz/src/components/HorizontalBarChart/Chart.tsx, packages/polaris-viz/src/components/HorizontalBarChart/HorizontalBarChart.tsx, packages/polaris-viz/src/components/LegendContainer/LegendContainer.tsx, packages/polaris-viz/src/components/LineChart/Chart.tsx, packages/polaris-viz/src/components/LineChart/LineChart.tsx, packages/polaris-viz/src/components/LineChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/LineChartPredictive/LineChartPredictive.tsx, packages/polaris-viz/src/components/LineChartPredictive/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/LineChartRelational/LineChartRelational.tsx, packages/polaris-viz/src/components/LineChartRelational/stories/playground/LegendPosition.stories.tsx, packages/polaris-viz/src/components/StackedAreaChart/Chart.tsx, packages/polaris-viz/src/components/StackedAreaChart/StackedAreaChart.tsx, packages/polaris-viz/src/components/StackedAreaChart/stories/playground/Playground.stories.tsx, packages/polaris-viz/src/components/VerticalBarChart/Chart.tsx, packages/polaris-viz/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/polaris-viz/src/types.ts
Added `labelPosition` to `BarChart`, `LineChart`, `LineChartPredictive`, `LineChartRelational` & `StackedAreaChart` to allow the legend to be rendered left, center or right aligned.
Resolves https://github.com/shop/issues-analytics/issues/1352
- [BarChart](https://6062ad4a2d14cd0021539c1b-biiqylypld.chromatic.com/?path=/story/polaris-viz-charts-barchart-playground--legend-position)
- [LineChartRelational](https://6062ad4a2d14cd0021539c1b-biiqylypld.chromatic.com/?path=/story/polaris-viz-charts-linechartrelational-playground-legendposition--legend-position)
- [LineChartPredictive](https://6062ad4a2d14cd0021539c1b-biiqylypld.chromatic.com/?path=/story/polaris-viz-charts-linechartpredictive-playground--legend-position)
- [LineChart](https://6062ad4a2d14cd0021539c1b-biiqylypld.chromatic.com/?p …
=> Add legendPosition to multiple charts

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/DonutChart/Chart.tsx, packages/polaris-viz/src/components/DonutChart/stories/TinySlices.stories.tsx
Added `padAngle` to `DonutChart` so that all slices will render even when then min/max values are wildly different.
Resolves https://github.com/Shopify/merchant-analytics-issues/issues/511
|---|---|
|![image](https://github.com/user-attachments/assets/0cf1efc9-0802-4be2-9528-ddfb2b181ee4)|![image](https://github.com/user-attachments/assets/d84d7588-5928-4a38-9f17-616f3eff1736)|
https://6062ad4a2d14cd0021539c1b-ntboeyaprp.chromatic.com/?path=/story/polaris-viz-chromatic-charts-donutchart--tiny-slices
=> Add padAngle to DonutChart

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/FunnelChartNext/components/FunnelChartLabels/FunnelChartLabels.tsx
We have to reduce the spacing between counts and trends when the funnel chart layouts display in the same line below the main percentage, so that we can delay having to wrap everything stacked. We also reduced the font size of the counts by 2px when in this layout.
https://github.com/user-attachments/assets/632a6db4-a177-4dbc-84fe-aa0c9cd390ee
http://localhost:6006/?path=/story/polaris-viz-charts-funnelchartnext--with-trend-indicators
=> Reduce spacing funnel trends

packages/polaris-viz/CHANGELOG.md, packages/polaris-viz/src/components/Annotations/components/AnnotationContent/AnnotationContent.tsx, packages/polaris-viz/src/types.ts
We can render `ReactNode` for the annotation content but the type only expected a `string`. Until we can overhaul annotations, we'll change the type to `ReactNode`.
=> Allow ReactNode to be passed to annotation content
